### ISSUE TITLE
Catmandu - a (meta)data toolkit

### ISSUE THREAD

**Issue by jwikle** [imls-dmt/resources-workflow#215]
Information about registered data management training resource

- [ ] Date resource added: 04/04/2019
- [ ] Registered by: jwikle
- [ ] Clearinghouse URL: http://dmtclearinghouse.esipfed.org/node/10380

Tracking: @karlbenedict @njhoebel
